// worker/state.js — Shared mutable state for the game worker

export const state = {
  GRID_W: 0,
  GRID_H: 0,
  NUM_BOTS: 0,
  CELLS_PER_TICK: 0,
  EXPANSION_TICK_MS: 0,
  BOT_THINK_MS: 0,
  isSpectateMode: false,
  boatsEnabled: false,
  grid: null,
  terrain: null,
  waterMag: null,
  waterComponent: null,
  playerStates: null,
  totalLandTiles: 0,
  playerPlaced: false,
  tileChanges: [],
  centersSumX: null,
  centersSumY: null,
  centersN: null,
  cities: [],
  citySet: new Set(),
  defensePosts: [],
  dpostSet: new Set(),
  econBuildings: [],
  econBuildingSet: new Set(),
  terrainClaimed: null,
  boats: [],
  destroyedDposts: [],
  paused: false,
};
